[project]
name = "qedmft"
packages = [{include = "qedmft", from = "src"}]
version = "0.1.1"
description = "cavity polaritons from electric field response"
authors = ["John Bonini <jrbp@user.noreply.github.com>"]
requires-python = ">=3.10"
dependencies = [
'numpy = "1.21.6"',
'matplotlib = "^3.5.1"',
'ipykernel = ^6.9.1',
'h5py = "3.10.0"'
]
