[tool.poetry]
packages = [{include = "qedmft", from = "src"}]
name = "qedmft"
version = "0.1.0"
description = ""
authors = ["John Bonini <jrbp@user.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"

numpy = "^1.21.6"
matplotlib = "^3.5.1"

ipykernel = {version = "^6.9.1", optional = true}
py4vasp = {git = "https://github.com/jrbp/p4vasp.git", branch = "no_mdtraj", optional = true}

[tool.poetry.extras]
jup = ["ipykernel"]
vaspio = ["py4vasp"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
